server:
  port: 8123
  servlet:
    # 上下文
    context-path: /api

spring:
  application:
    name: xin-picture-backend
    # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xin_picture
    username: root
    password: 123456


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: v1.0
    license: Apache 2.0
    group:
      defult:
        api-rule: package
        api-rule-resources:
          - com.yxchen.xinpicturebackend.controller